### ISSUE TITLE
Error due to using http instead of https

### ISSUE THREAD

**Issue by srghma** [owsas/nominatim#2]
Failed to load http://nominatim.openstreetmap.org/search?q=bakery%20in%20new%20york&format=json: Redirect from 'http://nominatim.openstreetmap.org/search?q=bakery%20in%20new%20york&format=json' to 'https://nominatim.openstreetmap.org/search?q=bakery%20in%20new%20york&format=json' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://vdare_feature_tests_be:3000' is therefore not allowed access.

**Comment by jcguarinpenaranda** [comment]
Hello, I'm checking back on these issues

Thank you so much for your contribution :)
